### ISSUE TITLE
Feat: Change the Issue/PR template to the newer form versions

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [krishdevdb/.github#1]
## Description

GitHub has introduced new issue template features. Now Issues templates can be forms, we can Implement that in this project as well what do you think?

## Screenshots

![](https://i2.wp.com/user-images.githubusercontent.com/1469659/122435700-20f37b00-cf90-11eb-8028-056c7449e555.gif?ssl=1)

**Comment by krishdevdb** [comment]
## Thank You

Thank you @kaiwalyakoparkar for your contribution to our project. We have reviewed your issue and we are adding those in #2 would you mind reviewing that before a merge is made?
